In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
#import  as
from sklearn.preprocessing import LabelEncoder, RobustScaler, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [49]:
data = pd.read_csv("E:\ML\AISS\hotel_booking_3_3010\hotel_bookings.csv")
data.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [3]:
data.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [27]:
data = data[['is_canceled', 'lead_time', 'country', 'market_segment', 'distribution_channel', 'previous_cancellations', 'deposit_type', 'agent', 'total_of_special_requests','reservation_status']]

In [28]:
#data.info()
data.dtypes

is_canceled                    int64
lead_time                    float64
country                        int32
market_segment                 int32
distribution_channel           int32
previous_cancellations       float64
deposit_type                   int32
agent                        float64
total_of_special_requests    float64
reservation_status             int32
dtype: object

In [29]:
#data.hist()
fig_dims = (50, 50)
fig, ax = plt.subplots(figsize=fig_dims)
hist = data.hist(bins=20, ax=ax) 
plt.savefig("hist.png")
#plt.show()
plt.close()

c:\users\sheetal\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:3296: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  exec(code_obj, self.user_global_ns, self.user_ns)

In [30]:
data.isnull().sum()

is_canceled                  0
lead_time                    0
country                      0
market_segment               0
distribution_channel         0
previous_cancellations       0
deposit_type                 0
agent                        0
total_of_special_requests    0
reservation_status           0
dtype: int64

In [31]:
data.shape
data.head()

,is_canceled,lead_time,country,market_segment,distribution_channel,previous_cancellations,deposit_type,agent,total_of_special_requests,reservation_status
0,0,1.922535,135,3,1,0.0,0,0.410443,0.0,1
1,0,4.704225,135,3,1,0.0,0,0.410443,0.0,1
2,0,-0.436620,59,3,1,0.0,0,0.410443,0.0,1
3,0,-0.394366,59,2,0,0.0,0,1.930070,0.0,1
4,0,-0.387324,59,6,3,0.0,0,1.482517,1.0,1

In [32]:
print(data.country.mode())
data.country = data.country.fillna("PRT")
print(data.agent.mean())
data.agent = data.agent.fillna(86.69338185346918)

0    135
dtype: int32
0.41044322974453984

In [33]:
data.isnull().sum()

is_canceled                  0
lead_time                    0
country                      0
market_segment               0
distribution_channel         0
previous_cancellations       0
deposit_type                 0
agent                        0
total_of_special_requests    0
reservation_status           0
dtype: int64

In [34]:
# data.previous_cancellations.unique()
# data.agent.unique()
# data.assigned_room_type.unique()
# data.booking_changes.unique()
# data.reserved_room_type.unique()
# data.previous_bookings_not_canceled.unique()
# data.distribution_channel.unique()
# data.market_segment.unique()

In [35]:
data.describe()

,is_canceled,lead_time,country,market_segment,distribution_channel,previous_cancellations,deposit_type,agent,total_of_special_requests,reservation_status
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,0.246559,93.161789,4.928101,2.585317,0.087118,0.124893,0.410443,0.571363,0.649803
std,0.482918,0.752557,44.665422,1.266726,0.907578,0.844336,0.334678,0.719687,0.792798,0.497776
min,0.000000,-0.485915,0.000000,0.000000,0.000000,0.000000,0.000000,-0.188811,0.000000,0.000000
25%,0.000000,-0.359155,56.000000,4.000000,3.000000,0.000000,0.000000,-0.132867,0.000000,0.000000
50%,0.000000,0.000000,81.000000,5.000000,3.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.640845,135.000000,6.000000,3.000000,0.000000,0.000000,0.867133,1.000000,1.000000
max,1.000000,4.704225,176.000000,7.000000,4.000000,26.000000,2.000000,3.545455,5.000000,2.000000

In [36]:
#data.boxplot()
fig_dims = (150, 150)
fig, ax = plt.subplots(figsize=fig_dims)
box = data.boxplot() 
plt.savefig("box.png")
#plt.show()
plt.close()

In [37]:
scaler = RobustScaler()
#scaler = StandardScaler()
#scaler = MinMaxScaler()
data[["lead_time","previous_cancellations", "agent", "total_of_special_requests"]] = scaler.fit_transform(data[["lead_time","previous_cancellations", "agent", "total_of_special_requests"]])

In [38]:
label_encoder = LabelEncoder()

In [39]:
data.head()

,is_canceled,lead_time,country,market_segment,distribution_channel,previous_cancellations,deposit_type,agent,total_of_special_requests,reservation_status
0,0,1.922535,135,3,1,0.0,0,0.410443,0.0,1
1,0,4.704225,135,3,1,0.0,0,0.410443,0.0,1
2,0,-0.436620,59,3,1,0.0,0,0.410443,0.0,1
3,0,-0.394366,59,2,0,0.0,0,1.930070,0.0,1
4,0,-0.387324,59,6,3,0.0,0,1.482517,1.0,1

In [41]:
data['country']= label_encoder.fit_transform(data['country']) 
data['market_segment']= label_encoder.fit_transform(data['market_segment']) 
data['distribution_channel']= label_encoder.fit_transform(data['distribution_channel']) 
data['deposit_type']= label_encoder.fit_transform(data['deposit_type']) 
#data['reservation_status_date']= label_encoder.fit_transform(data['reservation_status_date']) 
data['reservation_status']= label_encoder.fit_transform(data['reservation_status'])

In [42]:
data.describe()

,is_canceled,lead_time,country,market_segment,distribution_channel,previous_cancellations,deposit_type,agent,total_of_special_requests,reservation_status
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,0.246559,93.161789,4.928101,2.585317,0.087118,0.124893,0.410443,0.571363,0.649803
std,0.482918,0.752557,44.665422,1.266726,0.907578,0.844336,0.334678,0.719687,0.792798,0.497776
min,0.000000,-0.485915,0.000000,0.000000,0.000000,0.000000,0.000000,-0.188811,0.000000,0.000000
25%,0.000000,-0.359155,56.000000,4.000000,3.000000,0.000000,0.000000,-0.132867,0.000000,0.000000
50%,0.000000,0.000000,81.000000,5.000000,3.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.640845,135.000000,6.000000,3.000000,0.000000,0.000000,0.867133,1.000000,1.000000
max,1.000000,4.704225,176.000000,7.000000,4.000000,26.000000,2.000000,3.545455,5.000000,2.000000

In [43]:
X = data.drop("is_canceled", axis=1)
X.shape
X.head()

,lead_time,country,market_segment,distribution_channel,previous_cancellations,deposit_type,agent,total_of_special_requests,reservation_status
0,1.922535,135,3,1,0.0,0,0.410443,0.0,1
1,4.704225,135,3,1,0.0,0,0.410443,0.0,1
2,-0.436620,59,3,1,0.0,0,0.410443,0.0,1
3,-0.394366,59,2,0,0.0,0,1.930070,0.0,1
4,-0.387324,59,6,3,0.0,0,1.482517,1.0,1

In [44]:
#data['is_canceled'] = data['is_canceled'].astype(float)

In [45]:
y = data.is_canceled
y.shape
y.head()
X.dtypes

lead_time                    float64
country                        int64
market_segment                 int64
distribution_channel           int64
previous_cancellations       float64
deposit_type                   int64
agent                        float64
total_of_special_requests    float64
reservation_status             int64
dtype: object

In [46]:
classifier = RandomForestClassifier(n_estimators = 50)
classifier.fit(X, y)

RandomForestClassifier(n_estimators=50)

### RFA 99.99

In [47]:
# X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=0)
# print(X_train.shape, X_test.shape, y_train.shape, y_test.shape, X.shape, y.shape)

# classifier = RandomForestClassifier(n_estimators = 50)
# classifier.fit(X_train, y_train)
# y_pred = classifier.predict(X_test)

# # calculate accuracy
# print("\n\nConfusion Matrix: \n\n", confusion_matrix(y_test, y_pred))
# print ("\n\nAccuracy : \n\n", accuracy_score(y_test,y_pred)*100)
# print("\n\nReport : \n\n", classification_report(y_test, y_pred))

In [48]:
print(".............. GUI...............")

import tkinter as tk
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

# tkinter gui
root = tk.Tk()
root.title("AIS SOLUTIONS PVT LTD")
canvas1 = tk.Canvas(root, width=900, height=500)
canvas1.pack()
#labels and input boxes

label0 = tk.Label(root,text="HOTEL BOOKING PREDICTION")
canvas1.create_window(400,20,window=label0)
label0.config(font=("Times",25))

label17 = tk.Label(root,text="Previous Cancellations").place(x=30, y=100)
canvas1.create_window(30,100,window=label17)

entry17 = tk.Entry(root)
canvas1.create_window(300,100,window=entry17)
entry17.config(font=("Times",18))

label2 = tk.Label(root,text="Lead Time").place(x=30, y=130)
canvas1.create_window(30,130,window=label2)

entry2 = tk.Entry(root)
canvas1.create_window(300,130,window=entry2)
entry2.config(font=("Times",18))


label13 = tk.Label(root,text="Country").place(x=30, y=160)
canvas1.create_window(30,160,window=label13)

entry13 = tk.Entry(root)
canvas1.create_window(300,160,window=entry13)
entry13.config(font=("Times",18))

label13_0 = tk.Label(root,text="Please Select respective coutry code from documentation").place(x=30, y=190)



label15 = tk.Label(root,text="Distribution Channel").place(x=30, y=240)
canvas1.create_window(30,240,window=label15)

entry15 = tk.Entry(root)
canvas1.create_window(300,240,window=entry15)
entry15.config(font=("Times",18))

label15_0 = tk.Label(root,text="Enter 0=Corporate, 1=Direct, 2=GDS, 3=TA/TO, 4=Undefined").place(x=30, y=270)




label14 = tk.Label(root,text="Market Segment").place(x=30, y=320)
canvas1.create_window(30,320,window=label14)

entry14 = tk.Entry(root)
canvas1.create_window(300,320,window=entry14)
entry14.config(font=("Times",18))

label14_0 = tk.Label(root,text="Enter 0=Aviation, 1=Complementory, 2=Corporate, 3=Direct, 4=Groups, 5=Offline TA/TO, 6=Online TA 7=Undefined").place(x=30, y=350)
#....................



label22 = tk.Label(root,text="Deposit Type").place(x=450, y=100)
canvas1.create_window(450,100,window=label22)

entry22 = tk.Entry(root)
canvas1.create_window(720,100,window=entry22)
entry22.config(font=("Times",18))

label22_0 = tk.Label(root,text="Enter 0=No Deposit, 1=No Refund, 2=Refundable for Deposit Type").place(x=450, y=120)

label23 = tk.Label(root,text="Agent").place(x=450, y=170)
canvas1.create_window(450,170,window=label23)

entry23 = tk.Entry(root)
canvas1.create_window(720,170,window=entry23)
entry23.config(font=("Times",18))

#label23_0 = tk.Label(root,text="agent").place(x=450, y=200)

label28 = tk.Label(root,text="Total of Special Requests").place(x=450, y=200)
canvas1.create_window(450,200,window=label28)

entry28 = tk.Entry(root)
canvas1.create_window(720,200,window=entry28)
entry28.config(font=("Times",18))

label29 = tk.Label(root,text="Reservation Status").place(x=450, y=230)
canvas1.create_window(450,230,window=label29)

entry29 = tk.Entry(root)
canvas1.create_window(720,230,window=entry29)
entry29.config(font=("Times",18))

label29_0 = tk.Label(root,text="Enter 0=Cancelled, 1=Check-Out, 2=No Show").place(x=450, y=260)

# label30 = tk.Label(root,text="Reservation Status Date").place(x=450, y=310)
# canvas1.create_window(450,310,window=label30)

# entry30 = tk.Entry(root)
# canvas1.create_window(720,310,window=entry30)
# entry30.config(font=("Times",18))

#label30_0 = tk.Label(root,text="reservation_status_date").place(x=450, y=330)

# get review
def values():
    
    global lead_time
    lead_time = float(entry2.get())
    
    global country
    country = float(entry13.get())
    global market_segment
    market_segment = float(entry14.get())
    global distribution_channel
    distribution_channel = float(entry15.get())

    
    global previous_cancellations
    previous_cancellations = float(entry17.get())
    
    global deposit_type
    deposit_type = float(entry22.get())
    global agent
    agent = float(entry23.get())
    
    global total_of_special_requests
    total_of_special_requests = float(entry28.get())
    global reservation_status
    reservation_status = float(entry29.get())
#     global reservation_status_date
#     reservation_status_date = float(entry30.get())

    res = classifier.predict([[lead_time, country, market_segment, distribution_channel, previous_cancellations, deposit_type, agent,  total_of_special_requests, reservation_status]])

    prediction_res = ("Result :", res)
    label_prediction = tk.Label(root, text=prediction_res)
    canvas1.create_window(400,480,window=label_prediction)
    label_prediction.config(font=("Times",18))

button1 = tk.Button(root, text="Predict Hotel Booking ", command=values)
canvas1.create_window(400,430,window=button1)
button1.config(font=("Times",18))
root.resizable(0,0)

root.mainloop()

.............. GUI...............

In [ ]:
"""
COUNTRY NAME & RESPECTIVE COUNTRY CODE

['PRT' 'GBR' 'USA' 'ESP' 'IRL' 'FRA' 'ROU' 'NOR' 'OMN' 'ARG' 'POL' 'DEU'
 'BEL' 'CHE' 'CN' 'GRC' 'ITA' 'NLD' 'DNK' 'RUS' 'SWE' 'AUS' 'EST' 'CZE'
 'BRA' 'FIN' 'MOZ' 'BWA' 'LUX' 'SVN' 'ALB' 'IND' 'CHN' 'MEX' 'MAR' 'UKR'
 'SMR' 'LVA' 'PRI' 'SRB' 'CHL' 'AUT' 'BLR' 'LTU' 'TUR' 'ZAF' 'AGO' 'ISR'
 'CYM' 'ZMB' 'CPV' 'ZWE' 'DZA' 'KOR' 'CRI' 'HUN' 'ARE' 'TUN' 'JAM' 'HRV'
 'HKG' 'IRN' 'GEO' 'AND' 'GIB' 'URY' 'JEY' 'CAF' 'CYP' 'COL' 'GGY' 'KWT'
 'NGA' 'MDV' 'VEN' 'SVK' 'FJI' 'KAZ' 'PAK' 'IDN' 'LBN' 'PHL' 'SEN' 'SYC'
 'AZE' 'BHR' 'NZL' 'THA' 'DOM' 'MKD' 'MYS' 'ARM' 'JPN' 'LKA' 'CUB' 'CMR'
 'BIH' 'MUS' 'COM' 'SUR' 'UGA' 'BGR' 'CIV' 'JOR' 'SYR' 'SGP' 'BDI' 'SAU'
 'VNM' 'PLW' 'QAT' 'EGY' 'PER' 'MLT' 'MWI' 'ECU' 'MDG' 'ISL' 'UZB' 'NPL'
 'BHS' 'MAC' 'TGO' 'TWN' 'DJI' 'STP' 'KNA' 'ETH' 'IRQ' 'HND' 'RWA' 'KHM'
 'MCO' 'BGD' 'IMN' 'TJK' 'NIC' 'BEN' 'VGB' 'TZA' 'GAB' 'GHA' 'TMP' 'GLP'
 'KEN' 'LIE' 'GNB' 'MNE' 'UMI' 'MYT' 'FRO' 'MMR' 'PAN' 'BFA' 'LBY' 'MLI'
 'NAM' 'BOL' 'PRY' 'BRB' 'ABW' 'AIA' 'SLV' 'DMA' 'PYF' 'GUY' 'LCA' 'ATA'
 'GTM' 'ASM' 'MRT' 'NCL' 'KIR' 'SDN' 'ATF' 'SLE' 'LAO']
None
----------------------------------------------------------\
-------------------------------------------------------------

[135  59 169  51  76  56 139 124 127   6 133  43  15  29  34  66  81 123
  46 140 154  11  52  42  25  54 113  27 100 153   3  75  31 107 103 166
 148 101 134 149  30  12  23  99 162 174   1  80  40 175  37 176  48  91
  38  72   5 161  82  71  69  77  60   4  63 168  83  28  41  35  61  92
 121 106 171 152  55  86 128  73  94 131 144 155  13  20 126 158  47 108
 117   7  85  98  39  33  22 115  36 151 165  19  32  84 156 145  14 142
 173 132 138  50 130 110 116  49 105  79 170 125  21 102 157 163  44 150
  90  53  78  70 141  88 104  18  74 159 122  16 172 164  58  62 160  64
  87  97  65 112 167 118  57 111 129  17  95 109 119  24 136  26   0   2
 147  45 137  68  96   9  67   8 114 120  89 143  10 146  93]
None
"""